name: Build Python Package and Publish to CodeArtifact
on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output \
        name=version::$(grep '__version__ = ' src/docx/__init__.py | awk '{print $3}' | tr -d '"')
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine awscli
        pip install -r requirements-dev.txt
    - name: Testing
      run: make test
    - name: Build package
      run: |
        make clean
        make build
    - name: Publish package
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.version }}
        AWS_DEFAULT_REGION: ap-southeast-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws codeartifact login --tool twine --repository wsp-releases --domain wspdigital --domain-owner 649047142885
        twine upload --repository codeartifact dist/wsp_python_docx-$RELEASE_VERSION.tar.gz
